const DATABASE_NAME = "@gameplay";

const COLLETION_USERS = `${DATABASE_NAME}:user`;
const COLLETION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export { COLLETION_USERS, COLLETION_APPOINTMENTS };
